#!/bin/bash
# -*- bash -*-

#set -x

: << =cut

=head1 NAME

fhem_humidity_all - Plugin to automatically monitor all energyCalc readings from FHEM

=head1 CONFIGURATION

If your FHEM server's telnet service does not listen on localhost:7072, set it
like so in plugin.conf:

 [fhem_auto_*]
 env.fhem_host fhem.example.org
 env.fhem_port 8888

=head1 AUTHORS

=over

=item 2016.01.10 Initial version by Jochen Spieker <jrspieker@well-adjusted.de>

=back

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

fhem_host=${fhem_host:-localhost}
fhem_port=${fhem_port:-7072}

call_fhem() {
	echo "$@" | nc -q1 "$fhem_host" "$fhem_port" | while read line; do
		test -n "$line" && echo "$line"
	done
}

all_energyCalc_devices() {
	call_fhem "list energyCalc=[0-9.]+ NAME" | awk '{ print $1 }'
}

get_energyCalc_from_device() {
	call_fhem "{ ReadingsVal(\"${1}\", \"energyCalc\", -1) }"
}

case $1 in
	config)
        cat <<'EOF'
graph_title FHEM Power Usage (Derived) (auto)
graph_info This graph shows derived energyCalc readings from FHEM
graph_vlabel Power (W)
graph_category fhem_auto
graph_printf %.0lf
graph_args --base 1000
graph_data_size custom 7d, 30m for 30d, 2h for 365d, 1d for 3650d
EOF
		all_energyCalc_devices | while read device; do
			devname="$(echo "$device" | tr '[.]' '_')"
			echo "${devname}.label ${device}"
			echo "${devname}.min 0"
			echo "${devname}.type DERIVE"
		done

        exit 0
		;;
	autoconf)
		if echo "quit" | nc -q1 "$fhem_host" "$fhem_port" > /dev/null 2>&1 ; then
			echo "yes"
		else
			echo "no (Connection to ${fhem_host}:${fhem_port} failed.)"
		fi
		exit 0
		;;
esac 

all_energyCalc_devices | while read device; do
	# we need to round to int for DERIVE
	LC_ALL=C
	energy=$( echo "3600 * $(get_energyCalc_from_device ${device})" | bc )
	devname="$(echo "$device" | tr '[.]' '_')"
	echo "${devname}.value $(/usr/bin/printf '%.0f' ${energy})"
done

exit 0

