#!/bin/bash
# -*- bash -*-

#set -x

: << =cut

=head1 NAME

fhem_humidity_all - Plugin to automatically monitor all brightness readings from FHEM

=head1 CONFIGURATION

No special configuration is needed.

If trouble reading files, use:

 [traffic]
 user root

=head1 AUTHORS

=over

=item 2016.01.10 Initial version by Jochen Spieker <jrspieker@well-adjusted.de>

=back

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

call_fhem() {
	echo "$@" | nc -q1 localhost 7072 | while read line; do
		test -n "$line" && echo "$line"
	done
}

all_brightness_devices() {
	call_fhem "list brightness=[0-9.]+ NAME" | awk '{ print $1 }'
}

get_brightness_from_device() {
	call_fhem "{ ReadingsVal(\"${1}\", \"brightness\", 0) }"
}

case $1 in
	config)
        cat <<'EOF'
graph_title FHEM Brightness (auto)
graph_info This graph shows brightness readings from FHEM
graph_vlabel brightness
graph_category fhem_auto
graph_printf %6.0lf
graph_args --lower-limit 0 --upper-limit 255 --rigid
graph_data_size custom 7d, 30m for 30d, 2h for 365d, 1d for 3650d
graph_scale no
EOF
	all_brightness_devices | while read device; do
		echo "${device}.label ${device}"
	done

        exit 0
		;;
	autoconf)
		echo "yes"
		exit 0
		;;
esac 

all_brightness_devices | while read device; do
	echo "${device}.value $(get_brightness_from_device ${device})"
done

exit 0

