#!/bin/bash
# -*- bash -*-

#set -x

: << =cut

=head1 NAME

fhem_auto_reading_ - Plugin to automatically monitor specific readings from FHEM

=head1 CONFIGURATION

If your FHEM server's telnet service does not listen on localhost:7072, set it
like so in plugin.conf:

 [fhem_auto_*]
 env.fhem_host fhem.example.org
 env.fhem_port 8888

This is a wildcard plugin. To monitor a specific reading from FHEM, create a
symbolic link to this file. Example:

  ln -s <fhem-munin-plugins>/plugins/fhem_auto_reading_ \
        /etc/munin/plugins/fhem_auto_reading_power

Please note that this only works for readings that return a numeric value
(integer or decimal fraction). Readings that return values like "21 C" will
*not* work!

=head1 AUTHORS

=over

=item 2016.01.10 Initial version by Jochen Spieker <jrspieker@well-adjusted.de>

=back

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

fhem_host=${fhem_host:-localhost}
fhem_port=${fhem_port:-7072}

reading=${0##*_reading_}

call_fhem() {
	echo "$@" | nc -q1 "$fhem_host" "$fhem_port" | while read line; do
		test -n "$line" && echo "$line"
	done
}

all_devices() {
	call_fhem "list ${reading}=[0-9.]+ NAME" | awk '{ print $1 }'
}

get_value_from_device() {
	call_fhem "{ ReadingsVal(\"${1}\", \"${reading}\", -1) }"
}

case $1 in
	config)
        cat <<EOF
graph_title FHEM Reading ${reading} (auto)
graph_info This graph shows ${reading} readings from FHEM
graph_category fhem_auto
graph_printf %4.0lf
graph_data_size custom 7d, 30m for 30d, 2h for 365d, 1d for 3650d
EOF
		all_devices | while read device; do
			devname="$(echo "$device" | tr '[.]' '_')"
			echo "${devname}.label ${device}"
		done

        exit 0
		;;
	autoconf)
		if echo "quit" | nc -q1 "$fhem_host" "$fhem_port" > /dev/null 2>&1 ; then
			echo "yes"
		else
			echo "no (Connection to ${fhem_host}:${fhem_port} failed.)"
		fi
		exit 0
		;;
esac 

all_devices | while read device; do
	devname="$(echo "$device" | tr '[.]' '_')"
	echo "${devname}.value $(get_value_from_device ${device})"
done

exit 0

