#!/bin/bash
# -*- bash -*-

#set -x

: << =cut

=head1 NAME

fhem_humidity_all - Plugin to automatically monitor desired temperatures from FHEM

=head1 CONFIGURATION

No special configuration is needed.

If trouble reading files, use:

 [traffic]
 user root

=head1 AUTHORS

=over

=item 2016.01.10 Initial version by Jochen Spieker <jrspieker@well-adjusted.de>

=back

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

fhem_host=${fhem_host:-localhost}
fhem_port=${fhem_port:-7072}

call_fhem() {
	echo "$@" | nc -q1 "$fhem_host" "$fhem_port" | while read line; do
		test -n "$line" && echo "$line"
	done
}

all_target_temp_devices() {
	call_fhem "list desired-temp=[0-9.]+:FILTER=device!=.+ NAME" | \
		# skip peered devices in order to suppress dupes
		while read device device; do
			channel=$(call_fhem "{ InternalVal(\"${device}\", \"channel_02\", \"foo\") }")
			state=$(call_fhem "{ ReadingsVal(\"${channel}\", \"state\", \"\") }")
			if [ "$state" != "peered" ]; then
				echo "$device"
			fi
		done
}

get_target_temp_from_device() {
	call_fhem "{ ReadingsVal(\"${1}\", \"desired-temp\", 0) }"
}

case $1 in
	config)
        cat <<'EOF'
graph_title FHEM Desired Temperatures (auto)
graph_vlabel degrees Celsius
graph_scale no
graph_category fhem_auto
graph_info This graph shows temperature readings from FHEM
graph_data_size custom 7d, 30m for 30d, 2h for 365d, 1d for 3650d
graph_printf %6.1lf
EOF
		all_target_temp_devices | while read device; do
			echo "${device}.label ${device}"
		done

        exit 0
		;;
	autoconf)
		if echo "quit" | nc -q1 "$fhem_host" "$fhem_port" > /dev/null 2>&1 ; then
			echo "yes"
		else
			echo "no (Connection to ${fhem_host}:${fhem_port} failed.)"
		fi
		exit 0
		;;
esac 

all_target_temp_devices | while read device; do
	echo "${device}.value $(get_target_temp_from_device ${device})"
done

exit 0

