#!/bin/bash
# -*- bash -*-

#set -x

: << =cut

=head1 NAME

fhem_temp - Plugin to automatically monitor all temperature readings from FHEM

=head1 CONFIGURATION

If your FHEM server's telnet service does not listen on localhost:7072, set it
like so in plugin.conf:

 [fhem_auto_*]
 env.fhem_host fhem.example.org
 env.fhem_port 8888

=head1 AUTHORS

=over

=item 2016.01.10 Initial version by Jochen Spieker <jrspieker@well-adjusted.de>

=back

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

fhem_host=${fhem_host:-localhost}
fhem_port=${fhem_port:-7072}

call_fhem() {
	echo "$@" | nc -q1 "$fhem_host" "$fhem_port" | while read line; do
		test -n "$line" && echo "$line"
	done
}

all_temp_devices() {
	# filter for devices without parent device in order to avoid
	# measuring the same thing twice
	call_fhem "list temperature=[-0-9.]+:FILTER=device!=.+ NAME" | awk '{ print $1 }'
	call_fhem "list measured-temp=[-0-9.]+:FILTER=device!=.+ NAME" | awk '{ print $1 }' | \
		# skip peered devices in order to suppress dupes
		while read device; do
			channel=$(call_fhem "{ InternalVal(\"${device}\", \"channel_02\", \"foo\") }")
			state=$(call_fhem "{ ReadingsVal(\"${channel}\", \"state\", \"\") }")
			if [ "$state" != "peered" ]; then
				echo "$device"
			fi
		done
}

get_temp_from_device() {
	call_fhem "{ ReadingsVal(\"${1}\", \"measured-temp\", ReadingsVal(\"${1}\", \"temperature\", 0)) }"
}


case $1 in
	config)
        cat <<'EOF'
graph_title FHEM Temperatures (auto)
graph_vlabel degrees Celsius
graph_scale no
graph_category fhem_auto
graph_info This graph shows temperature readings from FHEM
graph_data_size custom 7d, 30m for 30d, 2h for 365d, 1d for 3650d
graph_printf %6.1lf
EOF
		all_temp_devices | while read device; do
			echo "${device}.label ${device}"
		done

        exit 0
		;;
	autoconf)
		if echo "quit" | nc -q1 "$fhem_host" "$fhem_port" > /dev/null 2>&1 ; then
			echo "yes"
		else
			echo "no (Connection to ${fhem_host}:${fhem_port} failed.)"
		fi
		exit 0
		;;
esac 

all_temp_devices | while read device; do
	echo "${device}.value $(get_temp_from_device ${device})"
done

exit 0

