#!/bin/bash
# -*- bash -*-

#set -x

: << =cut

=head1 NAME

fhem_auto_roommate_state - Plugin to automatically monitor the state of roomates and guests via the residents toolkit

=head1 CONFIGURATION

If your FHEM server's telnet service does not listen on localhost:7072, set it
like so in plugin.conf:

 [fhem_auto_*]
 env.fhem_host fhem.example.org
 env.fhem_port 8888

=head1 AUTHORS

=over

=item 2018.03.17 Initial version by Karsten Beßner <jihmcdra43nl@opayq.com>, based on work by Jochen Spieker

=back

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

fhem_host=${fhem_host:-localhost}
fhem_port=${fhem_port:-7072}

call_fhem() {
	echo "$@" | nc -q1 "$fhem_host" "$fhem_port" | while read line; do
		test -n "$line" && echo "$line"
	done
}

all_resident_devices() {
	call_fhem "list state=[a-z]+:FILTER=TYPE=ROOMMATE|GUEST NAME" | awk '{ print $1 }'
}

get_resident_state_from_device() {
	call_fhem "{ ReadingsVal(\"${1}\", \"state\", 0) }" | sed -e 's/home/0.9/' -e 's/absent/0.1/' -e 's/asleep/0.4/' -e 's/gone/0.03/' -e 's/none/0.03/' | awk '{ print $1 }'
}

case $1 in
	config)
        cat <<'EOF'
graph_title FHEM Residents status including roommates and guests
graph_vlabel state
graph_scale yes
graph_category fhem_auto
graph_info This graph shows the  state (present, absent, asleep) of the guests and roommates, where the states are represented by different values: 0.9: home, 0.4: asleep, 0.1: absent, 0.03: gone or none (for guests)
graph_data_size custom 7d, 30m for 30d, 2h for 365d, 1d for 3650d
graph_args --lower-limit 0.0 --upper-limit 1 --rigid
graph_printf %6.1lf
EOF
		all_resident_devices | while read device; do
			echo "${device}.label ${device}"
		done

        exit 0
		;;
	autoconf)
		if echo "quit" | nc -q1 "$fhem_host" "$fhem_port" > /dev/null 2>&1 ; then
			echo "yes"
		else
			echo "no (Connection to ${fhem_host}:${fhem_port} failed.)"
		fi
		exit 0
		;;
esac 

all_resident_devices | while read device; do
	echo "${device}.value $(get_resident_state_from_device ${device})"
done

exit 0

